/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.fms.api;

import com.fms.entity.DashBoard;
import com.fms.model.EventSummary1;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import reactor.core.publisher.Mono;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.CrossOrigin;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-01-22T18:02:22.909+05:30[Asia/Calcutta]")
@Api(value = "dashboard", description = "the dashboard API")
@CrossOrigin(origins="http://localhost:3000")
public interface DashboardApi {

    Logger log = LoggerFactory.getLogger(DashboardApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }
    @CrossOrigin
    @ApiOperation(value = "", nickname = "dashboard", notes = "get the event summary for logged in user", response = DashBoard.class, tags={ "fms login", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "event summary fetched", response = DashBoard.class),
        @ApiResponse(code = 404, message = "No DataFound") })
    @RequestMapping(value = "/dashboard/{userId}",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default Mono<ResponseEntity<DashBoard>> dashboard( @ApiParam(value = "",required=true) @PathVariable("userId") String userId
) {
//        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
//            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return Mono.just(new ResponseEntity<>(getObjectMapper().get().readValue("{\r\n  \"totalEvents\" : \"totalEvents\",\r\n  \"livesImpacted\" : \"livesImpacted\",\r\n  \"totalVolunteers\" : \"totalVolunteers\",\r\n  \"totalParticipants\" : \"totalParticipants\"\r\n}", DashBoard.class), HttpStatus.NOT_IMPLEMENTED));
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return Mono.just(new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR));
                }
//            }
//        } else {
//        	System.out.println("no accept header found");
//            log.warn("ObjectMapper or HttpServletRequest not configured in default DashboardApi interface so no example is generated");
//        }
        //return Mono.just(new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED));
    }

}
